server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: client-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/clients/**

        - id: savings-products
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/savings-products/**

        - id: savings-accounts
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/savings-accounts/**

        - id: fixed-deposits
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/fixed-deposits/**

        - id: ledger
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/ledger/**