spring.application.name=fineract-integration-service
server.port=8085

# Fineract connection details
fineract.base-url=https://localhost:8443/fineract-provider/api/v1
fineract.tenant-id=default
fineract.username=mifos
fineract.password=password